// alpha2 codes taken from: https://www.iban.com/country-codes
// ISO 639-1 codes taken from: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

  const countries = {
    'Afghanistan': { alpha2: 'AF', iso6391: 'af', astronomy: 'ستاره‌شناسی' },
    'Albania': { alpha2: 'AL', iso6391: 'sq', astronomy: 'astronomi' },
    'Algeria': { alpha2: 'DZ', iso6391: 'ar', astronomy: 'الفلك' },
    'American Samoa': { alpha2: 'AS', iso6391: 'sm', astronomy: 'astronomy' },
    'Andorra': { alpha2: 'AD', iso6391: 'ca', astronomy: 'astronomia' },
    'Angola': { alpha2: 'AO', iso6391: 'pt', astronomy: 'astronomia' },
    'Anguilla': { alpha2: 'AI', iso6391: 'en', astronomy: 'astronomy' },
    'Antarctica': { alpha2: 'AQ', iso6391: null, astronomy: 'astronomy' },
    'Antigua and Barbuda': { alpha2: 'AG', iso6391: 'en', astronomy: 'astronomy' },
    'Argentina': { alpha2: 'AR', iso6391: 'es', astronomy: 'astronomía' },
    'Armenia': { alpha2: 'AM', iso6391: 'hy', astronomy: 'աստղագետություն' },
    'Aruba': { alpha2: 'AW', iso6391: 'nl', astronomy: 'astronomie' },
    'Australia': { alpha2: 'AU', iso6391: 'en', astronomy: 'astronomy' },
    'Austria': { alpha2: 'AT', iso6391: 'de', astronomy: 'Astronomie' },
    'Azerbaijan': { alpha2: 'AZ', iso6391: 'az', astronomy: 'astronomiya' },
    'Bahamas': { alpha2: 'BS', iso6391: 'en', astronomy: 'astronomy' },
    'Bahrain': { alpha2: 'BH', iso6391: 'ar', astronomy: 'الفلك' },
    'Bangladesh': { alpha2: 'BD', iso6391: 'bn', astronomy: 'তারা বিজ্ঞান' },
    'Barbados': { alpha2: 'BB', iso6391: 'en', astronomy: 'astronomy' },
    'Belarus': { alpha2: 'BY', iso6391: 'be', astronomy: 'астрономія' },
    'Belgium': { alpha2: 'BE', iso6391: 'nl', astronomy: 'astronomie' },
    'Belize': { alpha2: 'BZ', iso6391: 'en', astronomy: 'astronomy' },
    'Benin': { alpha2: 'BJ', iso6391: 'fr', astronomy: 'astronomie' },
    'Bermuda': { alpha2: 'BM', iso6391: 'en', astronomy: 'astronomy' },
    'Bhutan': { alpha2: 'BT', iso6391: 'dz', astronomy: 'ཟི་མོར' },
    'Bolivia': { alpha2: 'BO', iso6391: 'es', astronomy: 'astronomía' },
    'Bonaire, Sint Eustatius and Saba': { alpha2: 'BQ', iso6391: 'nl', astronomy: 'astronomie' },
    'Bosnia and Herzegovina': { alpha2: 'BA', iso6391: 'bs', astronomy: 'astronomija' },
    'Botswana': { alpha2: 'BW', iso6391: 'en', astronomy: 'astronomy' },
    'Bouvet Island': { alpha2: 'BV', iso6391: null, astronomy: 'astronomy' },
    'Brazil': { alpha2: 'BR', iso6391: 'pt', astronomy: 'astronomia' },
    'British Indian Ocean Territory': { alpha2: 'IO', iso6391: 'en', astronomy: 'astronomy' },
    'Brunei Darussalam': { alpha2: 'BN', iso6391: 'ms', astronomy: 'astronomi' },
    'Bulgaria': { alpha2: 'BG', iso6391: 'bg', astronomy: 'астрономия' },
    'Burkina Faso': { alpha2: 'BF', iso6391: 'fr', astronomy: 'astronomie' },
    'Burundi': { alpha2: 'BI', iso6391: 'rn', astronomy: 'astronomiya' },
    'Cabo Verde': { alpha2: 'CV', iso6391: 'pt', astronomy: 'astronomia' },
    'Cambodia': { alpha2: 'KH', iso6391: 'km', astronomy: 'ពុទ្ធសភា' },
    'Cameroon': { alpha2: 'CM', iso6391: 'fr', astronomy: 'astronomie' },
    'Canada': { alpha2: 'CA', iso6391: 'en', astronomy: 'astronomy' },
    'Cayman Islands': { alpha2: 'KY', iso6391: 'en', astronomy: 'astronomy' },
    'Central African Republic': { alpha2: 'CF', iso6391: 'fr', astronomy: 'astronomie' },
    'Chad': { alpha2: 'TD', iso6391: 'fr', astronomy: 'astronomie' },
    'Chile': { alpha2: 'CL', iso6391: 'es', astronomy: 'astronomía' },
    'China': { alpha2: 'CN', iso6391: 'zh', astronomy: '天文学' },
    'Christmas Island': { alpha2: 'CX', iso6391: 'en', astronomy: 'astronomy' },
    'Cocos (Keeling) Islands': { alpha2: 'CC', iso6391: 'en', astronomy: 'astronomy' },
    'Colombia': { alpha2: 'CO', iso6391: 'es', astronomy: 'astronomía' },
    'Comoros': { alpha2: 'KM', iso6391: 'ar', astronomy: 'الفلك' },
    'Congo': { alpha2: 'CG', iso6391: 'fr', astronomy: 'astronomie' },
    'Congo (Democratic Republic of the)': { alpha2: 'CD', iso6391: 'fr', astronomy: 'astronomie' },
    'Cook Islands': { alpha2: 'CK', iso6391: 'en', astronomy: 'astronomy' },
    'Costa Rica': { alpha2: 'CR', iso6391: 'es', astronomy: 'astronomía' },
    'Croatia': { alpha2: 'HR', iso6391: 'hr', astronomy: 'astronomija' },
    'Cuba': { alpha2: 'CU', iso6391: 'es', astronomy: 'astronomía' },
    'Curaçao': { alpha2: 'CW', iso6391: 'nl', astronomy: 'astronomie' },
    'Cyprus': { alpha2: 'CY', iso6391: 'el', astronomy: 'αστρονομία' },
    'Czech Republic': { alpha2: 'CZ', iso6391: 'cs', astronomy: 'astronomie' },
    'Denmark': { alpha2: 'DK', iso6391: 'da', astronomy: 'astronomi' },
    'Djibouti': { alpha2: 'DJ', iso6391: 'fr', astronomy: 'astronomie' },
    'Dominica': { alpha2: 'DM', iso6391: 'en', astronomy: 'astronomy' },
    'Dominican Republic': { alpha2: 'DO', iso6391: 'es', astronomy: 'astronomía' },
    'Ecuador': { alpha2: 'EC', iso6391: 'es', astronomy: 'astronomía' },
    'Egypt': { alpha2: 'EG', iso6391: 'ar', astronomy: 'الفلك' },
    'El Salvador': { alpha2: 'SV', iso6391: 'es', astronomy: 'astronomía' },
    'Equatorial Guinea': { alpha2: 'GQ', iso6391: 'es', astronomy: 'astronomía' },
    'Eritrea': { alpha2: 'ER', iso6391: 'ti', astronomy: 'ጃንዞታ' },
    'Estonia': { alpha2: 'EE', iso6391: 'et', astronomy: 'astronoomia' },
    'Eswatini': { alpha2: 'SZ', iso6391: 'ss', astronomy: 'astronomy' },
    'Ethiopia': { alpha2: 'ET', iso6391: 'am', astronomy: 'የአስተዳደር' },
    'Falkland Islands (Malvinas)': { alpha2: 'FK', iso6391: 'en', astronomy: 'astronomy' },
    'Faroe Islands': { alpha2: 'FO', iso6391: 'fo', astronomy: 'astronomi' },
    'Fiji': { alpha2: 'FJ', iso6391: 'fj', astronomy: 'taubalevu' },
    'Finland': { alpha2: 'FI', iso6391: 'fi', astronomy: 'tähtitiede' },
    'France': { alpha2: 'FR', iso6391: 'fr', astronomy: 'astronomie' },
    'French Guiana': { alpha2: 'GF', iso6391: 'fr', astronomy: 'astronomie' },
    'French Polynesia': { alpha2: 'PF', iso6391: 'fr', astronomy: 'astronomie' },
    'French Southern Territories': { alpha2: 'TF', iso6391: 'fr', astronomy: 'astronomie' },
    'Gabon': { alpha2: 'GA', iso6391: 'fr', astronomy: 'astronomie' },
    'Gambia': { alpha2: 'GM', iso6391: 'en', astronomy: 'astronomy' },
    'Georgia': { alpha2: 'GE', iso6391: 'ka', astronomy: 'ასტრონომია' },
    'Germany': { alpha2: 'DE', iso6391: 'de', astronomy: 'Astronomie' },
    'Ghana': { alpha2: 'GH', iso6391: 'en', astronomy: 'astronomy' },
    'Gibraltar': { alpha2: 'GI', iso6391: 'en', astronomy: 'astronomy' },
    'Greece': { alpha2: 'GR', iso6391: 'el', astronomy: 'αστρονομία' },
    'Greenland': { alpha2: 'GL', iso6391: 'kl', astronomy: 'astronomi' },
    'Grenada': { alpha2: 'GD', iso6391: 'en', astronomy: 'astronomy' },
    'Guadeloupe': { alpha2: 'GP', iso6391: 'fr', astronomy: 'astronomie' },
    'Guam': { alpha2: 'GU', iso6391: 'en', astronomy: 'astronomy' },
    'Guatemala': { alpha2: 'GT', iso6391: 'es', astronomy: 'astronomía' },
    'Guernsey': { alpha2: 'GG', iso6391: 'en', astronomy: 'astronomy' },
    'Guinea': { alpha2: 'GN', iso6391: 'fr', astronomy: 'astronomie' },
    'Guinea-Bissau': { alpha2: 'GW', iso6391: 'pt', astronomy: 'astronomia' },
    'Guyana': { alpha2: 'GY', iso6391: 'en', astronomy: 'astronomy' },
    'Haiti': { alpha2: 'HT', iso6391: 'fr', astronomy: 'astronomie' },
    'Heard Island and McDonald Islands': { alpha2: 'HM', iso6391: null, astronomy: 'astronomy' },
    'Holy See': { alpha2: 'VA', iso6391: 'la', astronomy: 'astronomia' },
    'Honduras': { alpha2: 'HN', iso6391: 'es', astronomy: 'astronomía' },
    'Hong Kong': { alpha2: 'HK', iso6391: 'zh', astronomy: '天文学' },
    'Hungary': { alpha2: 'HU', iso6391: 'hu', astronomy: 'csillagászat' },
    'Iceland': { alpha2: 'IS', iso6391: 'is', astronomy: 'stjörnufræði' },
    'India': { alpha2: 'IN', iso6391: 'hi', astronomy: 'खगोलशास्त्र' },
    'Indonesia': { alpha2: 'ID', iso6391: 'id', astronomy: 'astronomi' },
    'Iran (Islamic Republic of)': { alpha2: 'IR', iso6391: 'fa', astronomy: 'اخترشناسی' },
    'Iraq': { alpha2: 'IQ', iso6391: 'ar', astronomy: 'الفلك' },
    'Ireland': { alpha2: 'IE', iso6391: 'ga', astronomy: 'réalteolaíocht' },
    'Isle of Man': { alpha2: 'IM', iso6391: 'gv', astronomy: 'astrology' },
    'Israel': { alpha2: 'IL', iso6391: 'he', astronomy: 'אסטרונומיה' },
    'Italy': { alpha2: 'IT', iso6391: 'it', astronomy: 'astronomia' },
    'Jamaica': { alpha2: 'JM', iso6391: 'en', astronomy: 'astronomy' },
    'Japan': { alpha2: 'JP', iso6391: 'ja', astronomy: '天文学' },
    'Jordan': { alpha2: 'JO', iso6391: 'ar', astronomy: 'الفلك' },
    'Kazakhstan': { alpha2: 'KZ', iso6391: 'kk', astronomy: 'тарату' },
    'Kenya': { alpha2: 'KE', iso6391: 'sw', astronomy: 'astronomia' },
    'Kiribati': { alpha2: 'KI', iso6391: 'en', astronomy: 'astronomy' },
    'Korea South': { alpha2: 'KR', iso6391: 'ko', astronomy: '천문학' },
    'Korea North': { alpha2: 'KP', iso6391: 'ko', astronomy: '천문학' },
    'Kuwait': { alpha2: 'KW', iso6391: 'ar', astronomy: 'الفلك' },
    'Kyrgyzstan': { alpha2: 'KG', iso6391: 'ky', astronomy: 'астраономия' },
    'Lao People\'s Democratic Republic': { alpha2: 'LA', iso6391: 'lo', astronomy: 'ຮັກຜິດສະວະ' },
    'Latvia': { alpha2: 'LV', iso6391: 'lv', astronomy: 'astronomija' },
    'Lebanon': { alpha2: 'LB', iso6391: 'ar', astronomy: 'الفلك' },
    'Lesotho': { alpha2: 'LS', iso6391: 'en', astronomy: 'astronomy' },
    'Liberia': { alpha2: 'LR', iso6391: 'en', astronomy: 'astronomy' },
    'Libya': { alpha2: 'LY', iso6391: 'ar', astronomy: 'الفلك' },
    'Liechtenstein': { alpha2: 'LI', iso6391: 'de', astronomy: 'Astronomie' },
    'Lithuania': { alpha2: 'LT', iso6391: 'lt', astronomy: 'astronomija' },
    'Luxembourg': { alpha2: 'LU', iso6391: 'lb', astronomy: 'Astronomie' },
    'Macao': { alpha2: 'MO', iso6391: 'zh', astronomy: '天文學' },
    'Madagascar': { alpha2: 'MG', iso6391: 'mg', astronomy: 'astronomia' },
    'Malawi': { alpha2: 'MW', iso6391: 'ny', astronomy: 'astronomy' },
    'Malaysia': { alpha2: 'MY', iso6391: 'ms', astronomy: 'astronomi' },
    'Maldives': { alpha2: 'MV', iso6391: 'dv', astronomy: 'ތައްޔޮލާން' },
    'Mali': { alpha2: 'ML', iso6391: 'fr', astronomy: 'astronomie' },
    'Malta': { alpha2: 'MT', iso6391: 'mt', astronomy: 'astronomija' },
    'Marshall Islands': { alpha2: 'MH', iso6391: 'mh', astronomy: 'astronomy' },
    'Martinique': { alpha2: 'MQ', iso6391: 'fr', astronomy: 'astronomy' },
    'Mauritania': { alpha2: 'MR', iso6391: 'ar', astronomy: 'الفلك' },
    'Mauritius': { alpha2: 'MU', iso6391: 'en', astronomy: 'astronomy' },
    'Mayotte': { alpha2: 'YT', iso6391: 'fr', astronomy: 'astronomie' },
    'Mexico': { alpha2: 'MX', iso6391: 'es', astronomy: 'astronomía' },
    'Micronesia (Federated States of)': { alpha2: 'FM', iso6391: 'en', astronomy: 'astronomy' },
    'Moldova': { alpha2: 'MD', iso6391: 'ro', astronomy: 'astronomie' },
    'Monaco': { alpha2: 'MC', iso6391: 'fr', astronomy: 'astronomie' },
    'Mongolia': { alpha2: 'MN', iso6391: 'mn', astronomy: 'сансар шинжлэх ухаан' },
    'Montenegro': { alpha2: 'ME', iso6391: 'sr', astronomy: 'астрономија' },
    'Montserrat': { alpha2: 'MS', iso6391: 'en', astronomy: 'astronomy' },
    'Morocco': { alpha2: 'MA', iso6391: 'ar', astronomy: 'الفلك' },
    'Mozambique': { alpha2: 'MZ', iso6391: 'pt', astronomy: 'astronomia' },
    'Myanmar': { alpha2: 'MM', iso6391: 'my', astronomy: 'တိမ်ပန်းကျွမ်း' },
    'Namibia': { alpha2: 'NA', iso6391: 'en', astronomy: 'astronomy' },
    'Nauru': { alpha2: 'NR', iso6391: 'na', astronomy: 'astronomy' },
    'Nepal': { alpha2: 'NP', iso6391: 'ne', astronomy: 'खगोलशास्त्र' },
    'Netherlands': { alpha2: 'NL', iso6391: 'nl', astronomy: 'astronomie' },
    'New Caledonia': { alpha2: 'NC', iso6391: 'fr', astronomy: 'astronomie' },
    'New Zealand': { alpha2: 'NZ', iso6391: 'en', astronomy: 'astronomy' },
    'Nicaragua': { alpha2: 'NI', iso6391: 'es', astronomy: 'astronomía' },
    'Niger': { alpha2: 'NE', iso6391: 'fr', astronomy: 'astronomie' },
    'Nigeria': { alpha2: 'NG', iso6391: 'en', astronomy: 'astronomy' },
    'Niue': { alpha2: 'NU', iso6391: 'niu', astronomy: 'astronomy' },
    'Norfolk Island': { alpha2: 'NF', iso6391: 'en', astronomy: 'astronomy' },
    'Northern Mariana Islands': { alpha2: 'MP', iso6391: 'en', astronomy: 'astronomy' },
    'Norway': { alpha2: 'NO', iso6391: 'no', astronomy: 'astronomi' },
    'Oman': { alpha2: 'OM', iso6391: 'ar', astronomy: 'الفلك' },
    'Pakistan': { alpha2: 'PK', iso6391: 'ur', astronomy: 'ستارہ شاستر' },
    'Palau': { alpha2: 'PW', iso6391: 'pau', astronomy: 'astronomy' },
    'Palestine, State of': { alpha2: 'PS', iso6391: 'ar', astronomy: 'الفلك' },
    'Panama': { alpha2: 'PA', iso6391: 'es', astronomy: 'astronomía' },
    'Papua New Guinea': { alpha2: 'PG', iso6391: 'en', astronomy: 'astronomy' },
    'Paraguay': { alpha2: 'PY', iso6391: 'es', astronomy: 'astronomía' },
    'Peru': { alpha2: 'PE', iso6391: 'es', astronomy: 'astronomía' },
    'Philippines': { alpha2: 'PH', iso6391: 'en', astronomy: 'astronomy' },
    'Pitcairn': { alpha2: 'PN', iso6391: 'en', astronomy: 'astronomy' },
    'Poland': { alpha2: 'PL', iso6391: 'pl', astronomy: 'astronomia' },
    'Portugal': { alpha2: 'PT', iso6391: 'pt', astronomy: 'astronomia' },
    'Puerto Rico': { alpha2: 'PR', iso6391: 'es', astronomy: 'astronomía' },
    'Qatar': { alpha2: 'QA', iso6391: 'ar', astronomy: 'الفلك' },
    'Republic of North Macedonia': { alpha2: 'MK', iso6391: 'mk', astronomy: 'астрономија' },
    'Romania': { alpha2: 'RO', iso6391: 'ro', astronomy: 'astronomie' },
    'Russian Federation': { alpha2: 'RU', iso6391: 'ru', astronomy: 'астрономия' },
    'Rwanda': { alpha2: 'RW', iso6391: 'rw', astronomy: 'astronomia' },
    'Réunion': { alpha2: 'RE', iso6391: 'fr', astronomy: 'astronomie' },
    'Saint Barthélemy': { alpha2: 'BL', iso6391: 'fr', astronomy: 'astronomie' },
    'Saint Helena, Ascension and Tristan da Cunha': { alpha2: 'SH', iso6391: 'en', astronomy: 'astronomy' },
    'Saint Kitts and Nevis': { alpha2: 'KN', iso6391: 'en', astronomy: 'astronomy' },
    'Saint Lucia': { alpha2: 'LC', iso6391: 'en', astronomy: 'astronomy' },
    'Saint Martin (French part)': { alpha2: 'MF', iso6391: 'fr', astronomy: 'astronomie' },
    'Saint Pierre and Miquelon': { alpha2: 'PM', iso6391: 'fr', astronomy: 'astronomie' },
    'Saint Vincent and the Grenadines': { alpha2: 'VC', iso6391: 'en', astronomy: 'astronomy' },
    'Samoa': { alpha2: 'WS', iso6391: 'sm', astronomy: 'astronomy' },
    'San Marino': { alpha2: 'SM', iso6391: 'it', astronomy: 'astronomia' },
    'Sao Tome and Principe': { alpha2: 'ST', iso6391: 'pt', astronomy: 'astronomia' },
    'Saudi Arabia': { alpha2: 'SA', iso6391: 'ar', astronomy: 'الفلك' },
    'Senegal': { alpha2: 'SN', iso6391: 'fr', astronomy: 'astronomie' },
    'Serbia': { alpha2: 'RS', iso6391: 'sr', astronomy: 'астрономија' },
    'Seychelles': { alpha2: 'SC', iso6391: 'fr', astronomy: 'astronomie' },
    'Sierra Leone': { alpha2: 'SL', iso6391: 'en', astronomy: 'astronomy' },
    'Singapore': { alpha2: 'SG', iso6391: 'en', astronomy: 'astronomy' },
    'Sint Maarten': { alpha2: 'SX', iso6391: 'nl', astronomy: 'astronomie' },
    'Slovakia': { alpha2: 'SK', iso6391: 'sk', astronomy: 'astronómia' },
    'Slovenia': { alpha2: 'SI', iso6391: 'sl', astronomy: 'astronomija' },
    'Solomon Islands': { alpha2: 'SB', iso6391: 'en', astronomy: 'astronomy' },
    'Somalia': { alpha2: 'SO', iso6391: 'so', astronomy: 'falastuurka' },
    'South Africa': { alpha2: 'ZA', iso6391: 'en', astronomy: 'astronomy' },
    'South Georgia and the South Sandwich Islands': { alpha2: 'GS', iso6391: 'en', astronomy: 'astronomy' },
    'South Sudan': { alpha2: 'SS', iso6391: 'en', astronomy: 'astronomy' },
    'Spain': { alpha2: 'ES', iso6391: 'es', astronomy: 'astronomía' },
    'Sri Lanka': { alpha2: 'LK', iso6391: 'si', astronomy: 'විද්‍යාලය' },
    'Sudan': { alpha2: 'SD', iso6391: 'ar', astronomy: 'الفلك' },
    'Suriname': { alpha2: 'SR', iso6391: 'nl', astronomy: 'astronomie' },
    'Svalbard and Jan Mayen': { alpha2: 'SJ', iso6391: 'no', astronomy: 'astronomi' },
    'Sweden': { alpha2: 'SE', iso6391: 'sv', astronomy: 'astronomi' },
    'Switzerland': { alpha2: 'CH', iso6391: 'de', astronomy: 'Astronomie' },
    'Syrian Arab Republic': { alpha2: 'SY', iso6391: 'ar', astronomy: 'الفلك' },
    'Taiwan': { alpha2: 'TW', iso6391: 'zh', astronomy: '天文学' },
    'Tajikistan': { alpha2: 'TJ', iso6391: 'tg', astronomy: 'астрономия' },
    'Tanzania, United Republic of': { alpha2: 'TZ', iso6391: 'sw', astronomy: 'astronomy' },
    'Thailand': { alpha2: 'TH', iso6391: 'th', astronomy: 'ดาราศาสตร์' },
    'Timor-Leste': { alpha2: 'TL', iso6391: 'pt', astronomy: 'astronomia' },
    'Togo': { alpha2: 'TG', iso6391: 'fr', astronomy: 'astronomie' },
    'Tokelau': { alpha2: 'TK', iso6391: 'en', astronomy: 'astronomy' },
    'Tonga': { alpha2: 'TO', iso6391: 'to', astronomy: 'laei' },
    'Trinidad and Tobago': { alpha2: 'TT', iso6391: 'en', astronomy: 'astronomy' },
    'Tunisia': { alpha2: 'TN', iso6391: 'ar', astronomy: 'الفلك' },
    'Turkey': { alpha2: 'TR', iso6391: 'tr', astronomy: 'astronomi' },
    'Turkmenistan': { alpha2: 'TM', iso6391: 'tk', astronomy: 'astronomiýa' },
    'Turks and Caicos Islands': { alpha2: 'TC', iso6391: 'en', astronomy: 'astronomy' },
    'Tuvalu': { alpha2: 'TV', iso6391: 'tvl', astronomy: 'astronomy' },
    'Uganda': { alpha2: 'UG', iso6391: 'en', astronomy: 'astronomy' },
    'Ukraine': { alpha2: 'UA', iso6391: 'uk', astronomy: 'астрономія' },
    'United Arab Emirates': { alpha2: 'AE', iso6391: 'ar', astronomy: 'الفلك' },
    'United Kingdom': { alpha2: 'GB', iso6391: 'en', astronomy: 'astronomy' },
    'United States': { alpha2: 'US', iso6391: 'en', astronomy: 'astronomy' },
    'Uruguay': { alpha2: 'UY', iso6391: 'es', astronomy: 'astronomía' },
    'Uzbekistan': { alpha2: 'UZ', iso6391: 'uz', astronomy: 'astronomiya' },
    'Vanuatu': { alpha2: 'VU', iso6391: 'bi', astronomy: 'astronomy' },
    'Venezuela (Bolivarian Republic of)': { alpha2: 'VE', iso6391: 'es', astronomy: 'astronomía' },
    'Viet Nam': { alpha2: 'VN', iso6391: 'vi', astronomy: 'thiên văn học' },
    'Wallis and Futuna': { alpha2: 'WF', iso6391: 'fr', astronomy: 'astronomie' },
    'Western Sahara': { alpha2: 'EH', iso6391: 'ar', astronomy: 'الفلك' },
    'Yemen': { alpha2: 'YE', iso6391: 'ar', astronomy: 'الفلك' },
    'Zambia': { alpha2: 'ZM', iso6391: 'en', astronomy: 'astronomy' },
    'Zimbabwe': { alpha2: 'ZW', iso6391: 'en', astronomy: 'astronomy' }
  };

  export default countries;