// constellations and images taken manually from Wikipedia

const starConstellations = {
    'Andromeda': 'https://upload.wikimedia.org/wikipedia/commons/8/87/Andromeda_IAU.svg',
    'Aries': 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Aries_IAU.svg',
    'Auriga': 'https://upload.wikimedia.org/wikipedia/commons/9/92/Auriga_IAU.svg',
    'Caelum': 'https://upload.wikimedia.org/wikipedia/commons/6/68/Caelum_IAU.svg',
    'Camelopardalis': 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Camelopardalis_IAU.svg',
    'Cancer': 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Cancer_IAU.svg',
    'Canes Venatici': 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Canes_Venatici_IAU.svg',
    'Canis Major': 'https://upload.wikimedia.org/wikipedia/commons/b/be/Canis_Major_IAU.svg',
    'Canis Minor': 'https://upload.wikimedia.org/wikipedia/commons/c/c9/Canis_Minor_IAU.svg',
    'Capricornus': 'https://upload.wikimedia.org/wikipedia/commons/9/95/Capricornus_IAU.svg',
    'Cassiopeia': 'https://upload.wikimedia.org/wikipedia/commons/e/e7/Cassiopeia_IAU.svg',
    'Centaurus': 'https://upload.wikimedia.org/wikipedia/commons/5/59/Centaurus_IAU.svg',
    'Cepheus': 'https://upload.wikimedia.org/wikipedia/commons/8/82/Cepheus_IAU.svg',
    'Columba': 'https://upload.wikimedia.org/wikipedia/commons/8/82/Columba_IAU.svg',
    'Coma Berenices': 'https://upload.wikimedia.org/wikipedia/commons/d/d2/Coma_Berenices_IAU.svg',
    'Corona Borealis': 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Corona_Borealis_IAU.svg',
    'Corvus': 'https://upload.wikimedia.org/wikipedia/commons/2/22/Corvus_IAU.svg',
    'Crater': 'https://upload.wikimedia.org/wikipedia/commons/a/ad/Crater_IAU.svg',
    'Cygnus': 'https://upload.wikimedia.org/wikipedia/commons/3/3c/Cygnus_IAU.svg',
    'Delphinus': 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Delphinus_IAU.svg',
    'Draco': 'https://upload.wikimedia.org/wikipedia/commons/b/b6/Draco_IAU.svg',
    'Equuleus': 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Equuleus_IAU.svg',
    'Gemini': 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Gemini_IAU.svg',
    'Lacerta': 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Lacerta_IAU.svg',
    'Leo Minor': 'https://upload.wikimedia.org/wikipedia/commons/1/18/Leo_Minor_IAU.svg',
    'Lepus': 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Lepus_IAU.svg',
    'Libra': 'https://upload.wikimedia.org/wikipedia/commons/7/76/Libra_IAU.svg',
    'Lupus': 'https://upload.wikimedia.org/wikipedia/commons/9/94/Lupus_IAU.svg',
    'Lynx': 'https://upload.wikimedia.org/wikipedia/commons/7/78/Lynx_IAU.svg',
    'Lyra': 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Lyra_IAU.svg',
    'Monoceros': 'https://upload.wikimedia.org/wikipedia/commons/c/c6/Monoceros_IAU.svg',
    'Orion': 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Orion_IAU.svg',
    'Perseus': 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Perseus_IAU.svg',
    'Piscis Austrinus': 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Piscis_Austrinus_IAU.svg',
    'Sagitta': 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Sagitta_IAU.svg',
    'Scorpius': 'https://upload.wikimedia.org/wikipedia/commons/3/38/Scorpius_IAU.svg',
    'Sextans': 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Sextans_IAU.svg',
    'Triangulum': 'https://upload.wikimedia.org/wikipedia/commons/8/81/Triangulum_IAU.svg',
    'Ursa Major': 'https://upload.wikimedia.org/wikipedia/commons/1/13/Ursa_Major_IAU.svg',
    'Ursa Minor': 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Ursa_Minor_IAU.svg',
    'Volans': 'https://upload.wikimedia.org/wikipedia/commons/d/d3/Volans_IAU.svg',
    'Vulpecula': 'https://upload.wikimedia.org/wikipedia/commons/7/75/Vulpecula_IAU.svg'
};

  export default starConstellations;