// constellations and images taken manually from Wikipedia

const starConstellations = {
    'Andromeda': 'https://upload.wikimedia.org/wikipedia/commons/8/87/Andromeda_IAU.svg',
    'Antlia': 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Antlia_IAU.svg',
    'Apus': 'https://upload.wikimedia.org/wikipedia/commons/f/f0/Apus_IAU.svg',
    'Aquarius': 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Aquarius_IAU.svg',
    'Aquila': 'https://upload.wikimedia.org/wikipedia/commons/f/fb/Aquila_IAU.svg',
    'Ara': 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Ara_IAU.svg',
    'Aries': 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Aries_IAU.svg',
    'Auriga': 'https://upload.wikimedia.org/wikipedia/commons/9/92/Auriga_IAU.svg',
    'Boötes': 'https://upload.wikimedia.org/wikipedia/commons/4/47/Bo%C3%B6tes_IAU.svg',
    'Caelum': 'https://upload.wikimedia.org/wikipedia/commons/6/68/Caelum_IAU.svg',
    'Camelopardalis': 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Camelopardalis_IAU.svg',
    'Cancer': 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Cancer_IAU.svg',
    'Canes Venatici': 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Canes_Venatici_IAU.svg',
    'Canis Major': 'https://upload.wikimedia.org/wikipedia/commons/b/be/Canis_Major_IAU.svg',
    'Canis Minor': 'https://upload.wikimedia.org/wikipedia/commons/c/c9/Canis_Minor_IAU.svg',
    'Capricornus': 'https://upload.wikimedia.org/wikipedia/commons/9/95/Capricornus_IAU.svg',
    'Carina': 'https://upload.wikimedia.org/wikipedia/commons/9/9b/Carina_IAU.svg',
    'Cassiopeia': 'https://upload.wikimedia.org/wikipedia/commons/e/e7/Cassiopeia_IAU.svg',
    'Centaurus': 'https://upload.wikimedia.org/wikipedia/commons/5/59/Centaurus_IAU.svg',
    'Cepheus': 'https://upload.wikimedia.org/wikipedia/commons/8/82/Cepheus_IAU.svg',
    'Cetus': 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Cetus_IAU.svg',
    'Chamaeleon': 'https://upload.wikimedia.org/wikipedia/commons/5/58/Chamaeleon_IAU.svg',
    'Circinus': 'https://upload.wikimedia.org/wikipedia/commons/d/de/Circinus_IAU.svg',
    'Columba': 'https://upload.wikimedia.org/wikipedia/commons/8/82/Columba_IAU.svg',
    'Coma Berenices': 'https://upload.wikimedia.org/wikipedia/commons/d/d2/Coma_Berenices_IAU.svg',
    'Corona Australis': 'https://upload.wikimedia.org/wikipedia/commons/0/03/Corona_Australis_IAU.svg',
    'Corona Borealis': 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Corona_Borealis_IAU.svg',
    'Corvus': 'https://upload.wikimedia.org/wikipedia/commons/2/22/Corvus_IAU.svg',
    'Crater': 'https://upload.wikimedia.org/wikipedia/commons/a/ad/Crater_IAU.svg',
    'Crux': 'https://upload.wikimedia.org/wikipedia/commons/c/cf/Crux_IAU.svg',
    'Cygnus': 'https://upload.wikimedia.org/wikipedia/commons/3/3c/Cygnus_IAU.svg',
    'Delphinus': 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Delphinus_IAU.svg',
    'Dorado': 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Dorado_IAU.svg',
    'Draco': 'https://upload.wikimedia.org/wikipedia/commons/b/b6/Draco_IAU.svg',
    'Equuleus': 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Equuleus_IAU.svg',
    'Eridanus': 'https://upload.wikimedia.org/wikipedia/commons/6/6b/Eridanus_IAU.svg',
    'Fornax': 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Fornax_IAU.svg',
    'Gemini': 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Gemini_IAU.svg',
    'Grus': 'https://upload.wikimedia.org/wikipedia/commons/3/31/Grus_IAU.svg',
    'Hercules': 'https://upload.wikimedia.org/wikipedia/commons/2/2a/Hercules_IAU.svg',
    'Horologium': 'https://upload.wikimedia.org/wikipedia/commons/6/6d/Horologium_IAU.svg',
    'Hydra': 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Hydra_IAU.svg',
    'Hydrus': 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Hydrus_IAU.svg',
    'Indus': 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Indus_IAU.svg',
    'Lacerta': 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Lacerta_IAU.svg',
    'Leo': 'https://upload.wikimedia.org/wikipedia/commons/5/56/Leo_IAU.svg',
    'Leo Minor': 'https://upload.wikimedia.org/wikipedia/commons/1/18/Leo_Minor_IAU.svg',
    'Lepus': 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Lepus_IAU.svg',
    'Libra': 'https://upload.wikimedia.org/wikipedia/commons/7/76/Libra_IAU.svg',
    'Lupus': 'https://upload.wikimedia.org/wikipedia/commons/9/94/Lupus_IAU.svg',
    'Lynx': 'https://upload.wikimedia.org/wikipedia/commons/7/78/Lynx_IAU.svg',
    'Lyra': 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Lyra_IAU.svg',
    'Mensa': 'https://upload.wikimedia.org/wikipedia/commons/6/69/Mensa_IAU.svg',
    'Microscopium': 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Microscopium_IAU.svg',
    'Monoceros': 'https://upload.wikimedia.org/wikipedia/commons/c/c6/Monoceros_IAU.svg',
    'Musca': 'https://upload.wikimedia.org/wikipedia/commons/d/dc/Musca_IAU.svg',
    'Norma': 'https://upload.wikimedia.org/wikipedia/commons/4/4d/Norma_IAU.svg',
    'Octans': 'https://upload.wikimedia.org/wikipedia/commons/7/76/Octans_IAU.svg',
    'Ophiuchus': 'https://upload.wikimedia.org/wikipedia/commons/6/65/Ophiuchus_IAU.svg',
    'Orion': 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Orion_IAU.svg',
    'Pavo': 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Pavo_IAU.svg',
    'Pegasus': 'https://upload.wikimedia.org/wikipedia/commons/f/f4/Pegasus_IAU.svg',
    'Perseus': 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Perseus_IAU.svg',
    'Phoenix': 'https://upload.wikimedia.org/wikipedia/commons/6/68/Phoenix_IAU.svg',
    'Pictor': 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Pictor_IAU.svg',
    'Pisces': 'https://upload.wikimedia.org/wikipedia/commons/2/21/Pisces_IAU.svg',
    'Piscis Austrinus': 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Piscis_Austrinus_IAU.svg',
    'Puppis': 'https://upload.wikimedia.org/wikipedia/commons/e/e2/Puppis_IAU.svg',
    'Pyxis': 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Pyxis_IAU.svg',
    'Reticulum': 'https://upload.wikimedia.org/wikipedia/commons/0/00/Reticulum_IAU.svg',
    'Sagitta': 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Sagitta_IAU.svg',
    'Sagittarius': 'https://upload.wikimedia.org/wikipedia/commons/5/54/Sagittarius_IAU.svg',
    'Scorpius': 'https://upload.wikimedia.org/wikipedia/commons/3/38/Scorpius_IAU.svg',
    'Sculptor': 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Sculptor_IAU.svg',
    'Scutum': 'https://upload.wikimedia.org/wikipedia/commons/5/58/Scutum_IAU.svg',
    'Serpens': 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Serpens_Caput_IAU.svg',
    'Sextans': 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Sextans_IAU.svg',
    'Taurus': 'https://upload.wikimedia.org/wikipedia/commons/e/e9/Taurus_IAU.svg',
    'Telescopium': 'https://upload.wikimedia.org/wikipedia/commons/b/b6/Telescopium_IAU.svg',
    'Triangulum': 'https://upload.wikimedia.org/wikipedia/commons/8/81/Triangulum_IAU.svg',
    'Triangulum Australe': 'https://upload.wikimedia.org/wikipedia/commons/f/f0/Triangulum_Australe_IAU.svg',
    'Tucana': 'https://upload.wikimedia.org/wikipedia/commons/3/33/Tucana_IAU.svg',
    'Ursa Major': 'https://upload.wikimedia.org/wikipedia/commons/1/13/Ursa_Major_IAU.svg',
    'Ursa Minor': 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Ursa_Minor_IAU.svg',
    'Vela': 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Vela_IAU.svg',
    'Virgo': 'https://upload.wikimedia.org/wikipedia/commons/f/f5/Virgo_IAU.svg',
    'Volans': 'https://upload.wikimedia.org/wikipedia/commons/d/d3/Volans_IAU.svg',
    'Vulpecula': 'https://upload.wikimedia.org/wikipedia/commons/7/75/Vulpecula_IAU.svg'
};

  export default starConstellations;